/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fhir_client;

public class App {
    // public String run_create_patient() {
    //     create_patient.run(); 
    //     return "Patient Created!";
    // }
    public String run_csv_upload() throws Exception{
        csvUpload.run();
        return "csv parsed and uploaded!"; 
    }
    public static void main(String[] args) throws Exception {
        // System.out.println(new App().run_create_patient());
        System.out.println(new App().run_csv_upload());
    }
}
