/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fhir_client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull(classUnderTest.run_create_patient(), "app should have a run");
    }
}
